title: Deepak Mahakale
email: deepakmahakale@gmail.com
description: >-
  Ruby on Rails Developer
baseurl: ""
url: "http://deepakmahakale.in"
twitter_username: deepakmahakale
github_username:  deepakmahakale
google_analytics: UA-86389306-2

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
social_links:
  facebook: deepakmahakale1
  github: deepakmahakale
  stackoverflow: 4758119/deepak-mahakale
  instagram: deepakmahakale
  linkedin: deepakmahakale
  twitter: deepakmahakale
