title: Deepak Mahakale
email: deepakmahakale@gmail.com
description: >-
  Ruby on Rails Developer
baseurl: ""
url: "http://deepakmahakale.in"
twitter_username: deepakmahakale
github_username:  deepakmahakale
google_analytics: UA-NNNNNNNN-N

plugins:
  - jekyll-feed
